FROM node:lts-alpine3.16 as angular
RUN npm i --location=global @angular/cli@14.1.0

FROM angular as init
WORKDIR /app 
COPY package.json .
RUN npm i

FROM init as source
COPY . .

FROM source as build
RUN npm run build

FROM nginx:1.23.1 
COPY --from=build /app/dist /usr/share/nginx/html
ENV WS_URL=http://localhost:4002/
ENV API_URL=http://localhost:4003/
COPY .docker/nginx.conf.tpl . 
ENTRYPOINT ["/bin/sh", "-c", "envsubst < nginx.conf.tpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
EXPOSE 80